### ISSUE TITLE
[FIX] Project 페이지 API 연동 이슈 해결

### ISSUE THREAD

**Issue by yymin1022** [DefCon-Apps/DefCon-FE#44]
Project 페이지의 Build Issue를 해결하여 테스트서버 배포를 진행하였습니다.
List 로딩 시 Itme이 무한으로 반복되어 추가되는 이슈가 존재합니다.
이외에 Click하여 Detail Page로 이동하는 등의 기능은 정상적으로 작동합니다.

**Comment by rdg1029** [comment]
무한 반복이라니..😱
확인이요
