### ISSUE TITLE
[DEV] Mobile UI 구현

### ISSUE THREAD

**Issue by yymin1022** [DefCon-Apps/DefCon-FE#56]
## Summary
Mobile 기기에서 렌더링할 UI를 구현합니다.

## Description
Mobile 기기에서의 UI 렌더링을 위해 CSS Media-Query를 이용하고,
Mobile에 최적화된 UI를 구성합니다.

**Comment by HarenKei** [comment]
CSS Media-Query.... react-responsive 라이브러리의 useMediaQuery Hook을 사용하고 있어요
