### ISSUE TITLE
[FIX] Project 페이지 Mobile 폰트 이슈 해결

### ISSUE THREAD

**Issue by yymin1022** [DefCon-Apps/DefCon-FE#63]
Project 페이지의 Mobile UI에서 폰트가 적용되지 않는 문제를 해결해주시기 바랍니다.

![Screenshot_20230208-033954](https://user-images.githubusercontent.com/12806229/217336019-c180e51f-cf55-42d6-8772-9eea1ee4b97b.png)

**Comment by rdg1029** [comment]
모바일 크롬에서만 저렇게 되네요😱
(다른 브라우저는 괜찮은 것 같은데..)
![Screenshot_20230208-071443_NAVER.jpg](https://user-images.githubusercontent.com/10252712/217378979-7052b3e3-51a5-4c06-8c5f-079167223972.jpg)
